final List<String> items = const [
  'Helwan',
  'Ain Helwan',
  'Helwan University',
  'Wadi Hof',
  'Hadayek Helwan',
  'El-Maasara',
  'Tora El-Asmant',
  'Kozzika',
  'Tora El-Balad',
  'Sakanat El-Maadi',
  'Maadi',
  'Hadayek El-Maadi',
  'Dar El-Salam',
  'El-Zahraa',
  'Mar Girgis',
  'El-Malek El-Saleh',
  'Al-Sayeda Zeinab',
  'Saad Zaghloul',
  'Sadat',
  'Nasser',
  'Orabi',
  'Al-Shohadaa',
  'Ghamra',
  'El-Demerdash',
  'Manshiet El-Sadr',
  'Kobri El-Qobba',
  'Hammamat El-Qobba',
  'Saray El-Qobba',
  'Hadayeq El-Zaitoun',
  'Helmeyet El-Zaitoun',
  'El-Matareyya',
  'Ain Shams',
  'Ezbet El-Nakhl',
  'El-Marg',
  'New El-Marg',
  'El-Mounib',
  'Sakiat Mekki',
  'Omm El-Misryeen',
  'Giza',
  'Faisal',
  'Cairo University',
  'Bohooth',
  'Dokki',
  'Opera',
  'Sadat',
  'Mohamed Naguib',
  'Ataba',
  'Al-Shohadaa',
  'Massara',
  'Rod El-Farag',
  'St. Teresa',
  'El-Khalafawy',
  'El-Mezallat',
  'Kolleyyet El-Zeraa',
  'Shubra El-Kheima',
  'Al-Ahram',
  'Koleyet El-Banat',
  'Cairo Stadium',
  'Cairo Fair',
  'Abbassiya',
  'Abdou Pasha',
  'El-Geish',
  'Bab El-Shaaria',
  'Ataba',
];
